POLL_TIME = 1
FAIL_VALUE = 0
MAX_USERNAME = 42
MAX_PASSWORD = 256
MAX_ROOM_NAME = 128

# Endpoints
LOGIN = 'login'
REGISTER = 'register'
GET_CHATROOMS = 'get_chatrooms'
JOIN_ROOM = 'join_room'
SEND_MESSAGE = 'send_message'

# Fields
MESSAGE = 'message'
CHATROOM = "chatroom"
ERROR = 'error'
USERNAME = 'username'
PASSWORD = 'password'
REPEATED_PASSWORD = 'repeated_password'

SERVER_HOST = 'SERVER_HOST'
SERVER_PORT = 'SERVER_PORT'
MESSAGE_DB_HOST = 'MESSAGE_DB_HOST'
MESSAGE_DB_PORT = 'MESSAGE_DB_PORT'
MESSAGE_DB_USER = 'MESSAGE_DB_USER'
MESSAGE_DB_PASS = 'MESSAGE_DB_PASS'
MESSAGE_DB_NAME = 'MESSAGE_DB_NAME'
MESSAGE_TABLE_NAME = 'message'
USER_TABLE_NAME = 'user'
CHATROOM_TABLE_NAME = 'chatroom'

POST = 'POST'
GET = 'GET'
SUCCESS = 'success'

CERT_PATH = "CERT_PATH"
KEY_PATH = "KEY_PATH"
