POLL_TIME = 1
FAIL_VALUE = 0
MAX_USERNAME = 42

# Endpoints
GET_CHATROOMS = 'get_chatrooms'

SERVER_HOST = 'SERVER_HOST'
SERVER_PORT = 'SERVER_PORT'
MESSAGE_DB_HOST = 'MESSAGE_DB_HOST'
MESSAGE_DB_PORT = 'MESSAGE_DB_PORT'
MESSAGE_DB_USER = 'MESSAGE_DB_USER'
MESSAGE_DB_PASS = 'MESSAGE_DB_PASS'
MESSAGE_DB_NAME = 'MESSAGE_DB_NAME'
MESSAGE_TABLE_NAME = 'message'
USER_TABLE_NAME = 'user'
CHATROOM_TABLE_NAME = 'chatroom'

POST = 'POST'
GET = 'GET'
SUCCESS = 'success'
ERROR = 'error'
MESSAGE = 'message'
CHATROOM = "chatroom"
